package com.gisnet.cancelacion.pojos;
// Generated 23/04/2015 09:05:31 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CNotario generated by hbm2java
 */
public class CNotario  implements java.io.Serializable {


     private long notarioId;
     private String CMunicipio;
     private String   entidad; 
     //private CUsuario CUsuario;
     private String nombreNotario;
     private Integer codigoNotario;
     private String notariaNumero;
     private int convenioInfonavit;
     private String email;
     private String telefono;
     private String calleNotaria;
     private String numeroCalle;
     private String coloniaNotaria;
     private Integer codigoPostalNotaria;

   
     private String codigoRespuesta;
     

    public CNotario() {
    }

	
    public CNotario(long notarioId) {
        this.notarioId = notarioId;
    }
    public CNotario(long notarioId, String CMunicipio, String nombreNotario, Integer codigoNotario, String notariaNumero, int convenioInfonavit, String email, String telefono, String calleNotaria, String numeroCalle, String coloniaNotaria, Integer codigoPostalNotaria) {
       this.notarioId = notarioId;
       this.CMunicipio = CMunicipio;
       //this.CUsuario = CUsuario;
       this.nombreNotario = nombreNotario;
       this.codigoNotario = codigoNotario;
       this.notariaNumero = notariaNumero;
       this.convenioInfonavit = convenioInfonavit;
       this.email = email;
       this.telefono = telefono;
       this.calleNotaria = calleNotaria;
       this.numeroCalle = numeroCalle;
       this.coloniaNotaria = coloniaNotaria;
       this.codigoPostalNotaria = codigoPostalNotaria;

    }
   
    public long getNotarioId() {
        return this.notarioId;
    }
    
    public void setNotarioId(long notarioId) {
        this.notarioId = notarioId;
    }
    public String getCMunicipio() {
        return this.CMunicipio;
    }
    
    public void setCMunicipio(String CMunicipio) {
        this.CMunicipio = CMunicipio;
    }

    public String getNombreNotario() {
        return this.nombreNotario;
    }
    
    public void setNombreNotario(String nombreNotario) {
        this.nombreNotario = nombreNotario;
    }
    public Integer getCodigoNotario() {
        return this.codigoNotario;
    }
    
    public void setCodigoNotario(Integer codigoNotario) {
        this.codigoNotario = codigoNotario;
    }
    public String getNotariaNumero() {
        return this.notariaNumero;
    }
    
    public void setNotariaNumero(String notariaNumero) {
        this.notariaNumero = notariaNumero;
    }
    public int getConvenioInfonavit() {
        return this.convenioInfonavit;
    }
    
    public void setConvenioInfonavit(int convenioInfonavit) {
        this.convenioInfonavit = convenioInfonavit;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCalleNotaria() {
        return this.calleNotaria;
    }
    
    public void setCalleNotaria(String calleNotaria) {
        this.calleNotaria = calleNotaria;
    }
    public String getNumeroCalle() {
        return this.numeroCalle;
    }
    
    public void setNumeroCalle(String numeroCalle) {
        this.numeroCalle = numeroCalle;
    }
    public String getColoniaNotaria() {
        return this.coloniaNotaria;
    }
    
    public void setColoniaNotaria(String coloniaNotaria) {
        this.coloniaNotaria = coloniaNotaria;
    }
    public Integer getCodigoPostalNotaria() {
        return this.codigoPostalNotaria;
    }
    
    public void setCodigoPostalNotaria(Integer codigoPostalNotaria) {
        this.codigoPostalNotaria = codigoPostalNotaria;
    }

    public String getCEntidad() {
        return entidad;
    }

    public void setCEntidad(String entidad) {
        this.entidad = entidad;
    }
    
    public String getEntidad() {
        return entidad;
    }

    public void setEntidad(String entidad) {
        this.entidad = entidad;
    }

    public String getCodigoRespuesta() {
        return codigoRespuesta;
    }

    public void setCodigoRespuesta(String codigoRespuesta) {
        this.codigoRespuesta = codigoRespuesta;
    }


}


